[2024-05-05T10:54:29.159+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T10:54:29.719+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog_api_pipeline.move_file scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-05-05T10:54:29.862+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog_api_pipeline.move_file scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-05-05T10:54:29.876+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T10:54:29.958+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): move_file> on 2024-04-04 00:00:00+00:00
[2024-05-05T10:54:29.992+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=18851) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T10:54:29.993+0000] {standard_task_runner.py:63} INFO - Started process 18960 to run task
[2024-05-05T10:54:30.009+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dog_api_pipeline', 'move_file', 'scheduled__2024-04-04T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/dog_api-pipeline.py', '--cfg-path', '/tmp/tmpv4u85oqw']
[2024-05-05T10:54:30.023+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask move_file
[2024-05-05T10:54:30.641+0000] {task_command.py:426} INFO - Running <TaskInstance: dog_api_pipeline.move_file scheduled__2024-04-04T00:00:00+00:00 [running]> on host b2b5d11d7cf5
[2024-05-05T10:54:31.771+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog_api_pipeline' AIRFLOW_CTX_TASK_ID='move_file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-04T00:00:00+00:00'
[2024-05-05T10:54:31.788+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T10:54:31.842+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-05T10:54:31.884+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '_move_file']
[2024-05-05T10:54:32.219+0000] {subprocess.py:86} INFO - Output:
[2024-05-05T10:54:32.270+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: _move_file: command not found
[2024-05-05T10:54:32.271+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-05T10:54:32.272+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T10:54:32.283+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-05T10:54:32.387+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dog_api_pipeline, task_id=move_file, execution_date=20240404T000000, start_date=20240505T105429, end_date=20240505T105432
[2024-05-05T10:54:32.519+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 60 for task move_file (Bash command failed. The command returned a non-zero exit code 127.; 18960)
[2024-05-05T10:54:32.693+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T10:54:32.868+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T10:54:32.899+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
